"""
    WriteToFile(describer) <: AbstractDescriber

Wraps another describer, and writes the generated description to the source file.

Useful if you're running an LLM to generate summaries and want to minimize cost!

Construct the object and pass it to the `plugin` kwarg of `makedocs`.

!!! warning
    This will write to files - but if you're running this in a CI pipeline, 
    then that won't propagate the changes to the branch or PR.

    If you're running this locally, then it's fine - just remember to commit the changes.

    Also, this won't work for generated files.

# Arguments
- `describer`: The describer to use to generate the description.
"""
struct WriteToFile{T} <: AbstractDescriber
    describer::T
end

function (plugin::WriteToFile)(page, doc)
    # Get the description from the underlying describer
    description = plugin.describer(page, doc)


    page_source_path = joinpath(doc.user.root, page.source)
    original_page = read(page_source_path, String)

    meta_block = """
        ```@meta
        # Auto-generated by DocumenterDescriptions.jl
        # Page hash $(sha256(original_page))
        Description = raw\"\"\"$description\"\"\"
        ```
        """

    final_text = original_page * "\n\n" * meta_block

    write(page_source_path, final_text)
end