name = "DocumenterDescriptions"
uuid = "e9159221-f9c0-48a0-ba53-9ba151c71a1d"
authors = ["Anshul Singhvi <anshul.singhvi@juliahub.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PromptingTools = "670122d1-24a8-4d70-bfce-740807c42192"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Documenter = "1.7"
PromptingTools = "0.72, 0.73"
TOML = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
